const CURATED_PROVIDER_MODELS: &[(&str, &[&str])] = &[
    (
        "openrouter",
        &[
            "openai/gpt-5.5",
            "openai/gpt-5.5-pro",
            "moonshotai/kimi-k2.6",
            "anthropic/claude-opus-4.7",
            "openai/gpt-5.4",
            "tencent/hy3-preview:free",
            "tencent/hy3-preview",
        ],
    ),
    (MOA_PROVIDER, &[MOA_DEFAULT_PRESET]),
    (
        "novita",
        &[
            "moonshotai/kimi-k2.5",
            "minimax/minimax-m2.7",
            "zai-org/glm-5",
            "deepseek/deepseek-v3-0324",
            "deepseek/deepseek-r1-0528",
            "qwen/qwen3-235b-a22b-fp8",
        ],
    ),
    (
        "nous",
        &[
            "openai/gpt-5.5-pro-20260423",
            "openai/gpt-5.5-pro",
            "openai/gpt-5.5",
            "anthropic/claude-4.7-opus-fast-20260512",
            "anthropic/claude-opus-4.7",
            "qwen/qwen3.6-max-preview-20260420",
            "qwen/qwen3.6-max-preview",
            "deepseek/deepseek-v4-pro",
            "moonshotai/kimi-k2.6",
            "nousresearch/hermes-3-llama-3.1-405b",
            "nousresearch/hermes-4-405b",
            "nousresearch/hermes-4-70b",
            "xiaomi/mimo-v2.5-pro",
            "tencent/hy3-preview",
            "anthropic/claude-sonnet-4.5",
        ],
    ),
    (
        "openai",
        &[
            "gpt-5.5",
            "gpt-5.5-pro",
            "gpt-4o",
            "gpt-4o-mini",
            "gpt-4.1",
            "gpt-5.4",
            "gpt-5.4-mini",
        ],
    ),
    (
        "anthropic",
        &[
            "claude-opus-4-6",
            "claude-sonnet-4-6",
            "claude-sonnet-4-5",
            "claude-haiku-4-5",
        ],
    ),
    (
        "bedrock",
        &[
            "anthropic.claude-sonnet-4-6",
            "us.anthropic.claude-sonnet-4-6",
            "anthropic.claude-haiku-4-5-20251001-v1:0",
            "us.anthropic.claude-haiku-4-5-20251001-v1:0",
            "anthropic.claude-3-5-sonnet-20241022-v2:0",
            "amazon.nova-pro-v1:0",
            "us.amazon.nova-pro-v1:0",
            "amazon.nova-micro-v1:0",
            "us.amazon.nova-micro-v1:0",
        ],
    ),
    (
        "opencode-go",
        &[
            "kimi-k2.6",
            "kimi-k2.5",
            "glm-5.1",
            "mimo-v2-pro",
            "mimo-v2-omni",
            "qwen3.6-plus",
            "qwen3.5-plus",
        ],
    ),
    (
        "opencode-zen",
        &[
            "kimi-k2.5",
            "gpt-5.4-pro",
            "claude-opus-4-6",
            "claude-sonnet-4-6",
            "gemini-3-pro",
            "kimi-k2-thinking",
        ],
    ),
    (
        "deepseek",
        &[
            "deepseek-chat",
            "deepseek-reasoner",
            "deepseek-v4-pro",
            "deepseek-v4-flash",
            "deepseek-v3.2",
            "deepseek-ai/deepseek-v3-2",
        ],
    ),
    ("xai", &["grok-build-0.1", "grok-4.3", "grok-3-mini"]),
    (
        "kilocode",
        &[
            "anthropic/claude-opus-4.6",
            "openai/gpt-5.4",
            "google/gemini-3-flash-preview",
        ],
    ),
    ("fireworks", &["accounts/fireworks-ai/qwq-32b"]),
    (
        "mistral",
        &["mistral-small", "mistral-large", "pixtral-large-latest"],
    ),
    ("togetherai", &["meta-llama/Llama-4-Maverick-17B"]),
    ("cohere", &["command-a", "command-r7b"]),
    (
        "perplexity",
        &["sonar-large-online", "pplx-70b-online", "pplx-7b-online"],
    ),
    ("groq", &["llama-3.3-70b-versatile", "llama-3.1-8b-instant"]),
    (
        "nvidia",
        &[
            "nvidia/llama-3.3-nemotron-super-49b-v1.5",
            "nvidia/nemotron-3-super-120b-a12b",
        ],
    ),
    (
        "ollama-local",
        &["qwen3:14b", "llama3.1:8b", "deepseek-r1:14b", "mistral:7b"],
    ),
    (
        "llama-cpp",
        &[
            "local-gguf",
            "qwen3-14b-instruct-q4_k_m.gguf",
            "llama-3.1-8b-instruct-q4_k_m.gguf",
        ],
    ),
    (
        "vllm",
        &[
            "NousResearch/Meta-Llama-3-8B-Instruct",
            "Qwen/Qwen3-14B-Instruct",
            "deepseek-ai/DeepSeek-V3.2",
        ],
    ),
    (
        "mlx",
        &[
            "mlx-community/Qwen3-8B-4bit",
            "mlx-community/Llama-3.1-8B-Instruct-4bit",
            "mlx-community/Mistral-7B-Instruct-v0.3-4bit",
        ],
    ),
    (
        "apple-ane",
        &[
            "ane-default",
            "foundation-model",
            "apple-on-device-openai-compatible",
        ],
    ),
    (
        "sglang",
        &[
            "default",
            "Qwen/Qwen3-14B-Instruct",
            "meta-llama/Llama-3.1-8B-Instruct",
        ],
    ),
    (
        "tgi",
        &[
            "default",
            "meta-llama/Llama-3.1-8B-Instruct",
            "Qwen/Qwen3-14B-Instruct",
        ],
    ),
    (
        "lmstudio",
        &["local-model", "qwen3", "llama-3.1-8b-instruct"],
    ),
    (
        "lmdeploy",
        &[
            "internlm/internlm2_5-7b-chat",
            "Qwen/Qwen3-14B-Instruct",
            "meta-llama/Llama-3.1-8B-Instruct",
        ],
    ),
    ("localai", &["local-model", "qwen3", "llama-3.1-8b"]),
    ("koboldcpp", &["local-model", "koboldcpp", "llama"]),
    (
        "text-generation-webui",
        &["local-model", "oobabooga", "llama"],
    ),
    ("tabbyapi", &["local-model", "exllamav2", "llama"]),
    (
        "huggingface",
        &[
            "moonshotai/Kimi-K2.5",
            "Qwen/Qwen3.5-397B-A17B",
            "deepseek-ai/DeepSeek-V3.2",
        ],
    ),
    (
        "gmi",
        &[
            "zai-org/GLM-5.1-FP8",
            "deepseek-ai/DeepSeek-V3.2",
            "moonshotai/Kimi-K2.5",
            "anthropic/claude-sonnet-4.6",
        ],
    ),
    (
        "arcee",
        &[
            "trinity-large-preview",
            "trinity-large-thinking",
            "trinity-mini",
        ],
    ),
    (
        "xiaomi",
        &[
            "mimo-v2.5-pro",
            "mimo-v2.5",
            "mimo-v2-pro",
            "mimo-v2-omni",
            "mimo-v2-flash",
        ],
    ),
    ("tencent-tokenhub", &["hy3-preview"]),
    ("zai", &["glm-5.2", "glm-5.1", "glm-5.0", "glm-4.5-flash"]),
    ("minimax", &["MiniMax-M3", "MiniMax-M2.7"]),
    ("minimax-cn", &["MiniMax-M3", "MiniMax-M2.7"]),
    (
        "gemini",
        &[
            "gemini-3.1-pro-preview",
            "gemini-3-pro-preview",
            "gemini-3.5-flash",
            "gemini-3.1-flash-lite-preview",
        ],
    ),
    (
        "google-gemini-cli",
        &[
            "gemini-3.1-pro-preview",
            "gemini-3-pro-preview",
            "gemini-3.5-flash",
        ],
    ),
    (
        "google",
        &[
            "gemini-3.1-pro-preview",
            "gemini-3-pro-preview",
            "gemini-3.5-flash",
        ],
    ),
];
